version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    labels:
      - "dependency"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    labels:
      - "dependency"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    labels:
      - "dependency"
